version: '2'
services:
    gatewayuaa-app:
        image: gatewayuaa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gatewayuaa-postgresql:5432/gatewayuaa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gatewayuaa-postgresql:
        extends:
            file: postgresql.yml
            service: gatewayuaa-postgresql
